### PR TITLE
added support for infinite running and tested with a modified version…

### PR DESCRIPTION
**Pull request by alan-stokes**
sorts out infinite runs and thus alows the push bot pull request to be compelted

### CODE REVIEW

**Comment by neworderofjamie** [comment]
Looks good

**Comment by alan-stokes** [comment]
did look good. bloody thing worked for infinite runs, now its refusing to work with finite runs. lol. the get spikes bruns horribly. Am currently assessing why (adding one extra param to system region should not have this kinda of effect).

**Comment by neworderofjamie** [comment]
should getSpikes work at all? you can't really record to SDRAM in an
infinite simulation...

**Comment by alan-stokes** [comment]
Hi Jamie, if you set up a infinite run with a reocrd, it blows up at run saying that it cant deal with infinite runs with reocrded regions (wait till buffer out comes along, and thatll disappear)

what the issue was, funnily enough, was a tie in with enums and counters. I'd added a element to the enum stating the infinite run, but there was a fixed constant sayign how many params are read by read_timing detials, i hadnt updated that. which meant that when recording got to find its sizes, it found zero, insrtead of sizes and this blew up get_spikes down stream due to random values in memory. lol. its fixed now and ive pushed the constant into the enum as descibred in your other fix, as it seems the better maintainable fix. 

given that, and your positive review beforehand. would you be happy for me to merge this now?

**Comment by neworderofjamie** [comment]
Hah, and that is an example of why you shouldn't have magic numbers for the
size of things :) Merge away

**Comment by AlexRast** [comment]
Isn't this a case for adding some sort of buffered recording for continuous 
runs? i.e. the recorder starts recording but as soon as it can outputs the data 
thus far collected to a host (where presumably it can be saved to disc or 
whatever)? This sort of functionality is going to become increasingly important 
in future, as people run ever-longer runs and what to see how the network is 
behaving. It's a sort of "semi-live" spike (or other data) output.

**Comment by alan-stokes** [comment]
mmmmmm.............and that exactly defines buffered out good sir. Talk to Sergio and ask when its going to be completed.

**Pull request merged**
