### PR TITLE
Factor out a common feature of our current GFE vertices

### PR DESCRIPTION
**Pull request by dkfellows**
The common feature is that they all use a single binary, and that binary uses the standard simulation interface to interact with the SpiNNaker runtime. This means that we can simply define the binary name in the constructor.

### CODE REVIEW

**Comment by rowleya** [comment]
Looks good to me, but I'll let Alan comment just in case...

**Comment by alan-stokes** [comment]
having looked at it. i like the idea, i think if your going to go down this route, you want a system_resources, so that it doesnt have to go to other constants when we start tracking dtcm properly. 

that all said. these things are meant to be examples for end users. Who wont be using a ide to begin with. Might even be using a notebook now. This brings me to a big gripe about how these classes have been restructured. By importing just the methods does indeed reduce footprint etc. But it makes teaching the blasted thing many times harder. Having, for example, data_utils.generate_system_data_region() instead of just generate_system_data_region(). it makes it obvious that these are not inside the class. You have no idea how often dribblers go where this function? so from that point of view, removal of all those "simplifcations" would need to be reverted. 

also, we have a  helpful_functions thing. why do we need a data_utils as well? cant we just plonk those functions in helpful functions?

**Comment by dkfellows** [comment]
Frankly, if I was doing this from scratch I'd make a class where that functionality was stapled inside (even if that stapling just delegates out to the real implementation elsewhere). Don't make them search all over; give them what they probably will need right there where their IDE will find it directly.

I don't mind this PR migrating to become that if we want it to.

**Comment by alan-stokes** [comment]
starting to try to clear some outstanding prs. This one still has the issues about "simplifcations" and id ask that this class that stapled everything inside is built and shown before this pr is considered fit for merging.

**Comment by alan-stokes** [comment]
whats the plans for this?

**Pull request merged**
