### PR TITLE
this makes the examples run in virtual machine mode. 

### PR DESCRIPTION
**Pull request by alan-stokes**
found by Jonas Faßbender

he should be making a issue soonish

### CODE REVIEW

**Comment by alan-stokes** [comment]
links to this issue: https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/issues/130

**Comment by rowleya** [comment]
That works... but AbstractSpiNNakerBase has a use_virtual_machine property that could also be exposed...

**Comment by alan-stokes** [comment]
mmmmmm........ it could do....... who uses that property anyhow?

**Comment by rowleya** [comment]
Probably no-one, but its use here makes more sense

**Comment by alan-stokes** [comment]
so having looked. it comes from the ConfigHandler and is a property already. and the gfe thus alredy has the property. good cacth

**Comment by alan-stokes** [comment]
no idea what ya complaining about ;-)

**Pull request merged**
