### PR TITLE
emergency fix for getting GFE working.

### PR DESCRIPTION
**Pull request by alan-stokes**
fixes for chip -power - monitor and gfe

### CODE REVIEW

**Comment by Christian-B** [comment]
Depends on:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/176

**Comment by andrewgait** [comment]
Any reason why the Conways/partitioned_example_c_vis_buffer example has been removed?

**Comment by alan-stokes** [comment]
heat demo and version c with vis never truely worked. 

conways with vis was a bodge to try and get it to work with tubertron, which we found couldn't work with the LPG nor was i inclined to go fix tuberon to use EIEIO. tubertron also forced placement constraints onto the machine, as it assumed x,y,p as a direct mapping to its vis space. So given the more forced issues of not being able to place on cores which are now reinjector / chip-power-monitor. it was just easier to remove and one day revisit it than to keep it around. 

heat demo is on the same wavelength, as it was trying to do a complete remap of heat demo into the GFE using all our interfaces, it failed due to these assumptions of application and machine mappings, which our tools try to hide away. Its also worth noting that we also have a heat demo from spinnaker tools and one that is in intro lab that goes though a backdoor via gfe onto the machine, but doesnt use any interfaces. so overall not worth keeping around

**Comment by andrewgait** [comment]
Sounds fine to me - just figured it was a good idea to have the reasoning documented somewhere.  :-)

**Pull request merged**
